language: java
jdk:
- openjdk8


script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: e0lgprZVymbcLSWtTrOmkoLemCn11ScbbnIC/T5dQ7PpruyYjt6iWXYS2BdhQ0xThTGjsg/5A19U9UU7TdZNayzcNQ8ZCm6DSlx/QdADiPxtAjw0NN3qTUEXh/faZWtcrQ+c9O1XYIW4svsiW8pfenHr9E8TyYJO7Y6MZsytusNhOEmnTUQ0XK9UhktXNyrP1jwpBJXqDYM3dAlxgOQ5SlEyPwzu5/dY0GVdx4qrqNgywDzv3wTgqOFXEZDshmfWL30xk/sjyLFpcY5/348NxBLLJqjzIsAtyDESS7dmzJhq7J0zDz8JVZg3AXcRaVzbGqPPT3DQP9LwlbLz4jfUgyd9B5jheLF17SspGDkgzJO4XhUCj3LpsAaAaeMaj2ccaTit6PEdlQRsRJY+qSPjwXpPOYmxg6ncxqiZHUr+tchNPem/B/1mdBAaX1yhulc2NNeBgo/MKR8LvNYBJlDmkS9ExPQ8DLxAmKPuQ+HZc/v6Z4oxu1rSIQrDIXcjXxlmzsuGrYDg8GvC0rPqtKhBrpE6l5dA9UUcXYyUr7ggFbbR43gl/q9ypwUxWtmQ1X8OsJgdAO1wCdtPCQefgFJrziw+m5OMXY9ym17VsOGo0tnMumg+HlxEGrAaYRJs/FNwQd+6csIQ1/PkVULcsl99ysafsCqkPsB6zIg0j/JgPUI=
  app: horse-battery-69
  on:
    repo: daniely211/BasicWebApp
