language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: o4Dfzjf/hg+CC+nMikb8qXmv4s7F6kA7BHUlPJVASYAv3s3fRyH+BoPPyPDvZiOYl5T6Kv2L4VpPryKlCn0gmtJeFsDDR0tSHm2zwKZNR4fdH7qoMKYeqWZbnGkXrlaR2u1YKbsRw4TjAAgLW7Ahi/kbPRjT1jJOZsNImcmkj3XG8T5kpm8mM5t22L3P633n4TNZaATtCL0V0Bo/OLloiz1pS0haOFxIVPm5YY1ldJguqLqFAisamm+B1xVyfqd7GKFtxR2vU+0ziuaxky9ePdHXG+D3AjdpkO7qXk+VvZur5Vj5SrDETVlUBh2SlrsIbJWCzevPF+5Eey+CJrs12rQjjTsQn7aiA+hSPffmlwN3fceepjrR9LRVrA3qczq0k/3VJsnrV9X6dFuyGI94FI9IrFpFkqHFNQ2wBy4zgzpTtNYQNy6VuBvw94NFqUMu6t81SAGBBciyowjB0OeG+Mfoxp9WsWbUQ6LrUotClDxHQv2eq2f2vAlsZx8e5PYct9JMyaJaW0/VoSNASolEJnji5qck702jXascfFhIXfLmDKiUo4g0cywfKEGI79lmwY4cng/86/bXf/92Y+Gxvjv82Ua0zl8UDYeKV3/8FhrWn2rgY3VAl/frTLB3EqXe7TltUo94inQ3d8QrWwvZ2dbMBNnrutA6cAEEoKbYpI8=
  app: horse-battery-69
  on:
    repo: daniely211/BasicWebApp
