language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: WNUn0Y6QG/IcalnvELu2RbOKielFxTsCbx0U3aI66YfUKpL7lDyGdx6R4o6uEzEsBWIj1FG4NgWVmBBJMjoLVUueiYAwVLHV436BYDsIDVXLYtBMA/+U4ETbh2CS0iXfZPwldpA7hJBomQiq1/yPpf+eTctW22pmDLwrl7OJ3xW+3Kl0yAgfI65Zfj1CMygwYHwxOt0B97c/ZQMmkWcB3LChYLVdZVcVZwpng+/yD0c0dSV6CtHYVVhEFDe1Z/5klohoe7z7QhNMogPMKI9zWOdwwm8QYf3k0JaxZLfWPJf2W4BkyE2xIp350YEg6Rs0CizaVSZ6pOCzdeELhG5W0uztPZTTSHYvyhVznFUOmkc2GBcw7GuihDKPEZzJyXakePEYqXs1GeoIWtaq+T1G7/9M0eCzJyAB+wozrXtI49S8sKvc2fnmFpsJQefMNASnAdJm8m7r/YX88wEr9RqSUe5afk99ViZN/dgowYClPiRgEnyWK0nPfp17z3ZgMoUdAmUbpGqRponja1UFJSlYQtyViNf7p6n+E2hFa2aAq8LO62DkVrbJIwwcSKeWfe1Gof8jSbF1UaLko144JxidRTn6ubAeuKM8Anb4Z4/9dT3uw0MBSl/PlrLbrkK8fHSzloI91AL/Jkj20x0F4X6vhG/fmKLmvM1vwt4L6Bg2jww=
  app: horse-battery-69
  on:
    repo: daniely211/BasicWebApp
