language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: iBCkoosZfwRxOQyvTYsX00SzQhIc0S2yYf4qOhTTqpN60ab4D20MsJV67JCBxSEp0SzzMdQ/2272TGeRsSvEoD6ydD4KRlJf2UU/AJyvo6C2W7rvTg2kMrTSf2z3J5xknwXhdbfmL+qy9bdEt2R621Xshu3wapxMO04IgGamL3DW0r0voyjIqS9541OYiTk2ItlrtbyDwQBfH6sejSkcnBanZaEVudyzEcQ/hDa92CRRYV6Lae5BtfbSF4FirGZ+PjLpEEZ0B7A1C5eqD/kDZjGe+nK6HTp4wsIlGVDgRZl4hHykXvHWAfO5iJyKlHcIQrj/+wGTMbxWQO2o2geRFvrXH9niF291uEEd25+gDuWpP5rIdyh/HpkOyLgne1h0qXv3PDZ4l1gYUYURAHeTcRjR0P6hVkJxVz0LMDRx48ydjIl+izt0JErEr0HWu2uSlTW7PpnSUkfvUWMeVpD8wvwYQg0NXNv4GNzojZq0oxbwO50WADJLLAXyzxSyFUoTQh6ldwAuvpUscG6EBKFXf17emXUzjuAN2zQALOKFJpaOa/l6gsWWIAKgsSSKejaAlxYnSvX3MT2yEnEL7papjP3ETSAxzBh0Uu8Ii2UhzyaeW6DOIObovxhGTvHSKuG7k4rKj9r9yocuZg6P6mSpI2Px+7td36f5PaxB4SCLrt4=
  app: horse-battery-69
  on:
    repo: daniely211/BasicWebApp
