language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure: iPZck6R8xXpcGykG0SpiEnDiuqGu05L6XPHhc4l58VpEmoNvMmwUcrmuaSs96JVVP1s/5u8S3Nu7utPL4ACnmE07X8s8q7OrvfJd9jNqU8EKdlD0/FDVH9roYPyKandXnFNcTE8JmiQXeye3tFNRsSM8Z6YxwDxzzZrgPTQPvcstsTSMbCIOQIMkp/Z9oBDeCBqJ5C9Jah1Ime22cHo99tVBvjAz7WNP8RZAVKhvfLVuZRZ9LhVTwTrwnE5PB9JzlET9469EGGTYN93j+W2uUZH9UYCnoAKf/tgTSacJ3jE2WHiRIpYoJa90yOYQ0OWPeprd7u2LtfKxKZzoes58/ENX+SXygnaCc2OZN/CvCEr78gFVNIJIHL1CV8GA0VUVvpH13wn8Bm/1/159TfRzcdkKJtrXE1BAaGmos/7CRhBSrOnQmO+2SuH6GOjqIY89XQ0S2yitaIkHF4cT1li5UU20h9bzPtVJ7IPELo/x39fsCTna//LVv/cxd0G8sdClnCOuYtK23mlemw5vhKH+BrVOcvYtI/JwRP8QhvTthGKpsui6ydFXZ7I82rUckHfnS32SRAF6CoW987gNXFDurQtniJUEY/FiCNtK48Hh1sDfffM+MsQmOEElM8ULwLOSwUr5CBhp3HpQZc5lvwj0/4l7pnscF5Q4C/p/vbhqg1E=
  app: horse-battery-69
