language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: AUsifocdfFrsxGPWHC8GuFgWQ2+Ta2K0dWHFSZXA7S84c6AOOWKVqooPJOusRpNqL7l/+yaigeEQpaKQ/k1DS0NCnM9ACgmY67uLwvbeAiGdmueXvjo6Hr4KNOjFHhNiNG4Ev3cbAgS9i2vJllBTAEpGEtQLQH8f8QGbLHA73c4n10fLNcmOyT97L30CV9OAJGPK9UMpgPM91UpJctzZ8wyxf3soA/nmzFx/RGspH5EqcdMs3vMk+ZhYkdZemrISfNebrUBT3wzHvh2qeSMCY78yoGlvLMhTweNto6raNelvB9cL+Kuo9lO8OeREeQ3muHmPgBWY8fctBy6HqEw4qcLvde9AxzURi4v7Ac8r4XuHXVqbhBC004mczVybgZ7wRBS1LPU9AzR4GNekGSZakDLj9ngNQUsEO2aIAXsdlBMm49tdmwxR7BIi19laZvqwc2NeKwziW0Yax/QeDxi4+K84I7omf5fhzVBIMfjGbdjV0unFmT85fCh71t3xX6Id1MkusMYcWUfuM2VX8rvL7FQzLLwQ5KD1JuuWW/wKN2N4nkiG4YogFYjEBKvrUPkXpEDNtpd1bstKJnFwXlt5UgsRHwd1+ytkA3lglIXXcqqmJvbpz5Umh1kvg0VxKVylmQQA+uEGCzXehcoPsReX+nng0b1ZJkMwVi/u4xATW04=
  app: horse-battery-69
  on:
    repo: daniely211/BasicWebApp
