language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: QnNBe2Vz86i5ymlfcBnmLb5Oc9BlXKETpi4gw8dzj/97hhcNeq29021ChA+Lo6TCQzL1YLNrDWV5ZkcZiZb3WJjXhnib9PIiUh1l0bI+30mu3qreuT2hYcnNwxLxrph9Ifps9Iw97JDOcNY7hrgqYb2oFyzf2edKnY8GhtmMyS/9ebwADLtTPT6rDUZ7BklzP4ofEQTO7/VmB6ffba6w7o7QauEcQ/zntbRMblNqYNJIhwbKu274DerxjLyw3HsRbC4TuKjGYcCzetSYvX5cH96D7wj9LnuRzeGCg7uIcigAR54pce7zAVINZx98BucFlDETEPNC0/pKS7X+5cZNjpABFHvmG3Jpi+RWIytHQf9z9vBGTiUuXfvuMqSFR311h36aCQ4unLgzSn1Su77xkAlpmBqpTHwdr7n1Tz2AC09QjG1lILUIoV9R1RRs4F6TsUr4Q27NcRWfJR0/eYJ1Q5QzGQLtljWSJalt8z1YPN5LiL1Uy05tlxohYVdvJl+ren38y/0iLKKi1KuM2CCkFC/rvw9sDPxGWgZssBSgk+dKwQ3pnhkOK9e9CBWQWpsTCSasjWCNz24oW0ee07HyrRzyyvgV4Vc07FwTdOZib2+8YZDmGrdGpMrxuymz6QQpWzQOxp8Zy8M0WidiMp+Yo12Q2qlmfwF9vPQU30mnL0k=
  app: horse-battery-69
  on:
    repo: daniely211/BasicWebApp
